using System;
using static System.Console;

namespace ProjectEulerLib
{
    public class Problem002
    {
        /*
            Each new term in the fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 term will be:
            1,2,3,5,8,13,21,34,55,89...
            by considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        */

        //double evenSum;

        public void SolveProblem()
        {
            FibonacciSequence();
        }
        public void FibonacciSequence()
        {
            double first = 1;
            double second = 2;
            double third;
            double limit = 33;
            double evenSum = 0;

            double currentLoop = 1;
            while (currentLoop < limit)
            {
                WriteLine(first);
                if(CheckIfEven(first)) evenSum += first;
                third = first + second;
                first = second;
                second = third;
                currentLoop++;
            }
            WriteLine($" the sum of even numbers is: {evenSum}");
        }
        public bool CheckIfEven(double number)
        {
            if ((number % 2) == 0) return true;
            else return false;
        }
    }
}